[general]
library_name = "libtest"
output_file_path = "./src/LibTest.jl"
module_name = "LibTest"
jll_pkg_name = "libtest_jll"
export_symbol_prefixes = ["libtest_"]
smart_de_anonymize = true
extract_c_comment_style = "doxygen"
show_c_function_prototype = true
output_ignorelist = [
]

auto_mutability = false
auto_mutability_with_new = false
auto_mutability_includelist = []

[codegen]
use_julia_bool = true
